# Generated by Django 6.0.7 on 2026-07-20 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_session_id', models.CharField(help_text='Match/lobby identifier', max_length=64)),
                ('sender_handle', models.CharField(max_length=64)),
                ('body', models.TextField()),
                ('sent_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('benign', 'Benign'), ('harassment', 'Harassment / Bullying'), ('hate_speech', 'Hate Speech'), ('threat', 'Threat of Violence'), ('sexual_content', 'Sexual Content'), ('grooming_risk', 'Grooming-Risk Language'), ('spam', 'Spam / Advertising'), ('cheating', 'Cheating / Exploit Discussion')], max_length=32)),
                ('severity', models.PositiveSmallIntegerField(help_text='0 (benign) - 100 (severe)')),
                ('rationale', models.TextField(help_text='Model-generated explanation for the classification')),
                ('confidence', models.FloatField(default=0.0, help_text='0.0 - 1.0 model confidence')),
                ('model_used', models.CharField(default='claude-sonnet-4-6', max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Cleared'), ('warned', 'Warning Issued'), ('muted', 'Muted'), ('banned', 'Banned')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='moderation.chatmessage')),
            ],
            options={
                'ordering': ['-severity', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModeratorAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(max_length=16)),
                ('new_status', models.CharField(max_length=16)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='moderation.classification')),
                ('moderator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
